In [47]:
import random
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [57]:
A = np.array([[ (5*i) + j for j in range(4)] for i in range(3)]) + 1
print(A)

print(A.shape)
print(A.ndim)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]
(3, 4)
2
