In [1]:
import random
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
A = np.array([
    [3, 7, 2, 9],
    [1, 5, 8, 4],
    [6, 0, 3, 2]
])

ans = ", ".join([str(A.ndim), str(A.shape), str(A.size), str(A.dtype)])
print(ans)

2, (3, 4), 12, int64


In [3]:
print(A[0])
print(A[:, 1])
print(A[1, 2:])
print(A[2, 2])

[3 7 2 9]
[7 5 0]
[8 4]
3


In [4]:
C = np.array([-10, 0, 10, 20, 30, 40])

F = (9/5) * C + 32
print(F)

[ 14.  32.  50.  68.  86. 104.]


In [5]:
x = np.array([10, 20, 30, 40, 50])
mu = x.mean()
sigma = x.std()
z = (x - mu) / sigma
print(z)
print(z.mean())
print(z.std())

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0
0.9999999999999999


In [6]:
measurements = np.array([
    [10, 12, 15, 11],
    [20, 18, 22, 21],
    [ 5,  7,  6,  8]
])

print("Sensor Averages: ", measurements.mean(axis=0))
print("Measurement Averages: ", measurements.mean(axis=1))
print("Sensor Maxes: ", measurements.max(axis=0))
print("Measurement Mins: ", measurements.min(axis=1))

Sensor Averages:  [11.66666667 12.33333333 14.33333333 13.33333333]
Measurement Averages:  [12.   20.25  6.5 ]
Sensor Maxes:  [20 18 22 21]
Measurement Mins:  [10 18  5]


In [7]:
temperature = np.array([
    21.5, 22.1, 19.8, 35.2,
    23.4, 41.7, 20.1, 18.9
])

print(temperature[temperature > 30])
print(temperature[temperature < 20])
print(temperature[(temperature >= 20) & (temperature <= 30)])
print(temperature[temperature > 30].size)

[35.2 41.7]
[19.8 18.9]
[21.5 22.1 23.4 20.1]
2


In [8]:
x = np.arange(1, 25)
print(x)
x = x.reshape(4, 6)
print(x)

print("First row: ", x[0])
print("Fifth column: ", x[:, 4])
print("Row means: ", x.mean(axis=1))
print("Column means: ", x.mean(axis=0))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
First row:  [1 2 3 4 5 6]
Fifth column:  [ 5 11 17 23]
Row means:  [ 3.5  9.5 15.5 21.5]
Column means:  [10. 11. 12. 13. 14. 15.]


In [9]:
measurements = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [20, 30, 40]
])
offsets = np.array([1, 2, 3])

measurements -= offsets
print("Measurements after offset subtraction:")
print(measurements)

scale = np.array([2, 1, 0.5])
measurements = measurements * scale
print("Measurements after scaling:")
print(measurements)

Measurements after offset subtraction:
[[ 9 18 27]
 [14 23 32]
 [19 28 37]]
Measurements after scaling:
[[18.  18.  13.5]
 [28.  23.  16. ]
 [38.  28.  18.5]]


In [10]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7,  8],
    [9, 10],
    [11, 12]
])

print(A@B)

[[ 58  64]
 [139 154]]


In [11]:
v = np.array([12, -5, 3])
speed = np.linalg.norm(v)
print(f"Speed: {speed:.2f}")
u = np.array([4, 2, -1])
dot = np.dot(v, u)
print(f"Dot product: {dot}")

Speed: 13.34
Dot product: 35


In [12]:
# 2x + 3y = 8
# 5x - y = 9

A = np.array([
    [2, 3],
    [5, -1]
])
b = np.array([8, 9])

x = np.linalg.solve(A, b)
print(f"Solution: x = {x[0]:.2f}, y = {x[1]:.2f}")
print(A @ x)

Solution: x = 2.06, y = 1.29
[8. 9.]


In [13]:
# 3x + 2y + z = 10
# 2x + 3y + 2z = 15
# x + 2y + 3z = 14

A = np.array([
    [3, 2, 1],
    [2, 3, 2],
    [1, 2, 3]
])
b = np.array([10, 15, 14])
x = np.linalg.solve(A, b)
print(x)
print(np.allclose(A @ x, b))

[0.5 3.  2.5]
True


In [14]:
A = np.array([
    [4, 7],
    [2, 6]
])
A_inv = np.linalg.inv(A)
print(A_inv)
print(A @ A_inv)
print(np.allclose(A @ A_inv, np.identity(2)))

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
True


In [15]:
A = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [1, 1, 1]
])
print(np.linalg.det(A))
print(np.linalg.matrix_rank(A))

# Rank is 2 because row 2 is a scalar multiple of row 1 and so isn't independent

0.0
2


In [16]:
data = np.array([
    [10, 20, 30],
    [12, 18, 33],
    [ 9, 21, 28],
    [15, 25, 40],
    [11, 19, 31]
])
# Columns = variables, Rows = experiments

d_mean = data.mean(axis=0)
print(f"Variable Means: {d_mean}")

d_std = data.std(axis=0)
print(f"Variable STDs: {d_std}")

z = (data - d_mean) / d_std
print(f"Standardized Data:\n{z}")

fvg11 = data[data[:, 0] > 11]
print(f"Experiments where first variable is greater than 11:\n{fvg11}")

norms = np.linalg.norm(data, axis=1)
print(f"Experiment Euclidean Norms: {norms}")

trans = data.T
print(f"Transposed Data:\n{trans}")

Variable Means: [11.4 20.6 32.4]
Variable STDs: [2.05912603 2.41660919 4.12795349]
Standardized Data:
[[-0.6799001  -0.24828177 -0.5814019 ]
 [ 0.29138576 -1.07588766  0.14535047]
 [-1.16554303  0.16552118 -1.06590348]
 [ 1.74831455  1.82073295  1.84110602]
 [-0.19425717 -0.66208471 -0.33915111]]
Experiments where first variable is greater than 11:
[[12 18 33]
 [15 25 40]]
Experiment Euclidean Norms: [37.41657387 39.45883931 36.138622   49.49747468 37.98683983]
Transposed Data:
[[10 12  9 15 11]
 [20 18 21 25 19]
 [30 33 28 40 31]]
